In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from scipy import stats


import nltk
nltk.download('stopwords')
from nltk.corpus import *
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer


from sklearn.metrics.pairwise import cosine_similarity

[nltk_data] Error loading stopwords: <urlopen error [WinError 10054]
[nltk_data]     An existing connection was forcibly closed by the
[nltk_data]     remote host>

In [4]:
df = pd.read_csv("Instagram data.csv")
df.head()

,Date,Impressions,From Home,From Hashtags,From Explore,From Other,Saves,Comments,Shares,Likes,Profile Visits,Follows,Conversion Rate,Caption,Hashtags
0,2021-12-10,3920,2586,1028,619,56,98,9,5,162,35,2,5.714286,Here are some of the most important data visua...,#finance #money #business #investing #investme...
1,2021-12-11,5394,2727,1838,1174,78,194,7,14,224,48,10,20.833333,Here are some of the best data science project...,#healthcare #health #covid #data #datascience ...
2,2021-12-12,4021,2085,1188,0,533,41,11,1,131,62,12,19.354839,Learn how to train a machine learning model an...,#data #datascience #dataanalysis #dataanalytic...
3,2021-12-13,4528,2700,621,932,73,172,10,7,213,23,8,34.782609,Here’s how you can write a Python program to d...,#python #pythonprogramming #pythonprojects #py...
4,2021-12-14,2518,1704,255,279,37,96,5,4,123,8,0,0.000000,Plotting annotations while visualizing your da...,#datavisualization #datascience #data #dataana...

In [10]:
dffinal = df[["Caption","Hashtags"]]

In [11]:
dffinal

,Caption,Hashtags
0,Here are some of the most important data visua...,#finance #money #business #investing #investme...
1,Here are some of the best data science project...,#healthcare #health #covid #data #datascience ...
2,Learn how to train a machine learning model an...,#data #datascience #dataanalysis #dataanalytic...
3,Here’s how you can write a Python program to d...,#python #pythonprogramming #pythonprojects #py...
4,Plotting annotations while visualizing your da...,#datavisualization #datascience #data #dataana...
...,...,...
171,Here is a list of 100+ Machine Learning Algori...,#machinelearning #machinelearningalgorithms #d...
172,A data science project report is a document us...,#datascience #datasciencejobs #datasciencetrai...
173,Here are some of the best Data Science project...,#datascience #datasciencejobs #datasciencetrai...
174,Analyzing the data collected on your fitness i...,#datascience #datasciencejobs #datasciencetrai...
175,Here are some of the best Code Editors and IDE...,#python #pythonprogramming #pythoncode #python...

In [12]:
dffinal.head()

,Caption,Hashtags
0,Here are some of the most important data visua...,#finance #money #business #investing #investme...
1,Here are some of the best data science project...,#healthcare #health #covid #data #datascience ...
2,Learn how to train a machine learning model an...,#data #datascience #dataanalysis #dataanalytic...
3,Here’s how you can write a Python program to d...,#python #pythonprogramming #pythonprojects #py...
4,Plotting annotations while visualizing your da...,#datavisualization #datascience #data #dataana...

In [13]:
captions = dffinal["Caption"].tolist()

In [14]:
vectors = TfidfVectorizer(stop_words="english")

In [15]:
matrix = vectors.fit_transform(captions)

In [17]:
ma = cosine_similarity(matrix)

In [26]:
def recommend(x):
    return ",".join(dffinal["Caption"].loc[x.argsort()[-5:-1]])

In [27]:
dffinal["recommend_post"] = [recommend(x) for x in ma]

dffinal

,Caption,Hashtags,recommend_post
0,Here are some of the most important data visua...,#finance #money #business #investing #investme...,Here are some of the most important tools that...
1,Here are some of the best data science project...,#healthcare #health #covid #data #datascience ...,Here are some of the best data science project...
2,Learn how to train a machine learning model an...,#data #datascience #dataanalysis #dataanalytic...,Data Science Use Cases: Here’s how Zomato is u...
3,Here’s how you can write a Python program to d...,#python #pythonprogramming #pythonprojects #py...,Here’s how to write a Python function to rever...
4,Plotting annotations while visualizing your da...,#datavisualization #datascience #data #dataana...,Practice these 90+ Data Science Projects For B...
...,...,...,...
171,Here is a list of 100+ Machine Learning Algori...,#machinelearning #machinelearningalgorithms #d...,Here is a list of 100+ Machine Learning Algori...
172,A data science project report is a document us...,#datascience #datasciencejobs #datasciencetrai...,"If you are a Data Science student, you must ha..."
173,Here are some of the best Data Science project...,#datascience #datasciencejobs #datasciencetrai...,Here are some of the best data science project...
174,Analyzing the data collected on your fitness i...,#datascience #datasciencejobs #datasciencetrai...,Here are some of the best data science project...
175,Here are some of the best Code Editors and IDE...,#python #pythonprogramming #pythoncode #python...,175 Python Projects with Source Code solved an...

In [31]:
dffinal["recommend_post"][5]

'Here are some of the most important data visualizations that every Financial Data Analyst/Scientist should know.,Here are some of the most important skills you need for your first data science job.,Here are some of the most important data visualizations that every data scientist must know.,Here are some of the most important soft skills that every data scientist should have.'